#
# Copyright (C) 2025-2026 BabyFire <babyfire@email.com>
#
# Licensed to the public under the GPL V3 License.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-kms
PKG_VERSION:=1.0
PKG_RELEASE:=1

LUCI_TITLE:=Key Management Service
LUCI_DEPENDS:=+kms +luci-base

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
